version: "3"
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    container_name: "freiDB"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=FALSE
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80
      - DB_PORT=5432
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  metabase:
    # TODO / IDEA: own metabase image with user and DB already configured
    image: metabase/metabase
    container_name: metabase_freigabe
    ports:
      - "3000:3000"
    depends_on:
      - db
      - api
  db:
    image: postgres
    container_name: fd-freigabe-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "54320:5432"
