"""matstämme table hinzugefügt

Revision ID: faed6c5f3975
Revises: ebec7cae170e
Create Date: 2020-08-07 11:30:43.898450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faed6c5f3975'
down_revision = 'ebec7cae170e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materialstamm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turbine_new', sa.String(length=250), nullable=False),
    sa.Column('turbine_alt', sa.String(length=250), nullable=False),
    sa.Column('stufe', sa.String(length=100), nullable=False),
    sa.Column('prozessmatstamm', sa.String(length=100), nullable=False),
    sa.Column('technologie', sa.String(length=250), nullable=False),
    sa.Column('beschichtung', sa.String(length=250), nullable=False),
    sa.Column('werkstoff', sa.String(length=250), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prozessmatstamm')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materialstamm')
    # ### end Alembic commands ###
