"""table Freigabe

Revision ID: 6c4716434a03
Revises: 42642243bde9
Create Date: 2020-08-06 12:41:47.969236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4716434a03'
down_revision = '42642243bde9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freigabe', sa.Column('Bemerkung', sa.String(length=1000), nullable=True))
    op.add_column('freigabe', sa.Column('Fertigungsaufträge', sa.String(length=500), nullable=True))
    op.add_column('freigabe', sa.Column('Freigabe_gültig_für_n_Ansätze', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freigabe', 'Freigabe_gültig_für_n_Ansätze')
    op.drop_column('freigabe', 'Fertigungsaufträge')
    op.drop_column('freigabe', 'Bemerkung')
    # ### end Alembic commands ###
