"""empty message

Revision ID: d6c9996b7d60
Revises: e95c14c0c9af
Create Date: 2020-08-06 12:10:33.795548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c9996b7d60'
down_revision = 'e95c14c0c9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freigabe', sa.Column('Auflagen', sa.Boolean(), nullable=False))
    op.add_column('freigabe', sa.Column('Freigabe', sa.String(length=250), nullable=False))
    #op.add_column('freigabe', sa.Column('Freigabeart', sa.Enum('auftragsbezogen', 'vorläufig', 'endgültig', 'Pilot-Lot', 'gesperrt', name='VARCHAR'), nullable=True))
    op.drop_constraint('freigabe_name_key', 'freigabe', type_='unique')
    op.create_unique_constraint(None, 'freigabe', ['Freigabe'])
    op.drop_column('freigabe', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freigabe', sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'freigabe', type_='unique')
    op.create_unique_constraint('freigabe_name_key', 'freigabe', ['name'])
    op.drop_column('freigabe', 'Freigabeart')
    op.drop_column('freigabe', 'Freigabe')
    op.drop_column('freigabe', 'Auflagen')
    # ### end Alembic commands ###
