"""table Freigabe

Revision ID: 311b2dcbb20c
Revises: 6c4716434a03
Create Date: 2020-08-06 13:02:40.689366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311b2dcbb20c'
down_revision = '6c4716434a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freigabe', sa.Column('name', sa.String(length=250), nullable=False))
    op.drop_constraint('freigabe_Freigabe_key', 'freigabe', type_='unique')
    op.create_unique_constraint(None, 'freigabe', ['name'])
    op.drop_column('freigabe', 'Freigabe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freigabe', sa.Column('Freigabe', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'freigabe', type_='unique')
    op.create_unique_constraint('freigabe_Freigabe_key', 'freigabe', ['Freigabe'])
    op.drop_column('freigabe', 'name')
    # ### end Alembic commands ###
